models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - "$PWD:/app"
    ports:
      - "8001:8000"
    command: bash -c "python /app/dining/manage.py makemigrations && python /app/dining/manage.py migrate && python /app/dining/manage.py loaddata /app/dining/fixtures/fixture.json && mod_wsgi-express start-server --working-directory /app/dining --reload-on-changes /app/dining/dining/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - "$PWD:/app"
   command: bash -c "mod_wsgi-express start-server --working-directory /app/dining --reload-on-changes /app/dining/dining/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - "$PWD:/app"
   command: bash -c "mod_wsgi-express start-server --working-directory /app/dining --reload-on-changes /app/dining/dining/wsgi.py"
